Feat/schemas
Carpool-Tech/carpool-app pull request #20
Opened 2023-12-27 16:53 UTC by marianaantunes

2023-12-27 17:35 UTC, maykelnekel commented on app/libs/realm/schemas/car.ts
acredito que o valor defatult para o número de lugares no carro deveria ser 4, já que o motorista sempre irá ocupar um espaço.
Isso pode facilitar o processo em algum momento.

2023-12-27 18:25 UTC, maykelnekel commented on app/libs/realm/schemas/user.ts
não vejo problemas em usarmos date_of_birth ao invés de birth_date ou algo semelhante.

2023-12-27 18:27 UTC, maykelnekel requested changes
No geral parece tudo muito bom, fiz dois comentários, um em car.ts e outro em user.ts

2023-12-27 21:06 UTC, marianaantunes commented on app/libs/realm/schemas/car.ts
Mas será que isso vai ficar claro para o usuário quando ele for colocar o valor?

2023-12-28 14:21 UTC, maykelnekel commented on app/libs/realm/schemas/car.ts
Eu acredito que sim, pois na minha concepção isso está atrealdo literalmente ao espaço disponível no carro, e se deve ser algo disponível, logo não posso contar comigo caso eu seja motorista.
Basicamente o que entendo é que esse valor definirá quantos lugares estarão disponíveis no carro.

2023-12-28 14:21 UTC, maykelnekel commented on app/libs/realm/schemas/car.ts
@nekelpatrick Conseguiria confirmar isso para nós?

2023-12-28 14:32 UTC, maykelnekel requested changes
Acredito que conseguimos melhorar a importação dos schemas, para que nosso app.tsx fique mais limpo.
Para isso podemos criar um index.ts do nosso subdiretório de schemas e exportar todos os schemas a partir dele.

deverá ficar algo parecido com isso no index.ts

```
// ../schemas/index.ts

const schemas = {
 User,
 Car,
 ...
}

export default schemas
```

```
// app.tsx
import schemas from "app/libs/realm/schemas"

<RealmProvider
              schema={[schemas.Historic, schemas.User, ...]}
              sync={{
         ...
  >
```
Ou até mesmo podemos já exportar como uma lista ao invés de um objeto.

2023-12-28 14:56 UTC, maykelnekel commented on App.tsx
Acredito que conseguimos melhorar a importação dos schemas, para que nosso app.tsx fique mais limpo.
Para isso podemos criar um index.ts do nosso subdiretório de schemas e exportar todos os schemas a partir dele.

deverá ficar algo parecido com isso no index.ts

```
// ../schemas/index.ts

const schemas = {
 User,
 Car,
 ...
}

export default schemas
```

```
// app.tsx
import schemas from "app/libs/realm/schemas"

<RealmProvider
              schema={[schemas.Historic, schemas.User, ...]}
              sync={{
         ...
  >
```
Ou até mesmo podemos já exportar como uma lista ao invés de um objeto.

2023-12-28 15:06 UTC, marianaantunes commented on App.tsx
ótima ideia, vou fazer isso

2023-12-28 17:32 UTC, maykelnekel approved these changes
Agora me parece tudo dentro dos conformes inclusive os schemas foram criados no banco, para mim está aprovado.

2023-12-28 20:11 UTC, marianaantunes commented on app/libs/realm/schemas/car.ts
acho que ele não vai conseguir olhar tão cedo, e o @andreDosSantosNascimento comentou no slack que não precisa olhar, então vou deixar assim mesmo e quando isso entrar em pauta a gente decide

2023-12-28 20:13 UTC, merged