Feat/Input
Carpool-Tech/carpool-app pull request #34
Opened 2024-01-24 21:56 UTC by marianaantunes

- O componente Input utiliza o TextInput do React Native
- Temos nele 4 estados: empty, valid, error e success
- Também tem a prop disabled
- Como ainda não definimos como serão as validações ainda, achei que os testes ficariam sem muito sentido

Também fiz algumas limpezas no código utilizando o linter e o prettier

2024-01-25 12:38 UTC, maykelnekel requested changes
Para mim está tudo certo, com exceção de uma dúvida que fiquei no arquivo app/components/IconBox/styles.ts

Mas relacionado ao componente em sí, achei que está muito bem estruturado. E as mudanças que foram feitas em outros arquivos não ligados à esse componente fazem sentido.

2024-01-25 12:38 UTC, maykelnekel commented on app/components/IconBox/styles.ts
é impressão minha, ou foi deletado o estilo desse componente?

2024-01-25 14:50 UTC, marianaantunes commented on app/components/IconBox/styles.ts
haha, jaja vou verificar isso

2024-01-25 14:50 UTC, marianaantunes commented on app/components/IconBox/styles.ts
mas acredito q tenha sido um rebase errado mesmo

2024-01-25 16:30 UTC, marianaantunes commented on app/components/IconBox/styles.ts
Ah, agora q eu olhei, foi deletado sim, eu achei que tinha conversado com voce sobre isso alias

2024-01-25 16:38 UTC, maykelnekel commented on app/components/IconBox/styles.ts
verdade, você comentou comigo mesmo, eu tinha esquecido disso.
Então beleza

2024-01-25 16:39 UTC, maykelnekel requested changes
Percebi que está havendo um conflito. Precisamos resolver ele antes de fazer o Merge

2024-01-26 13:23 UTC, maykelnekel approved these changes
Tudo ok para mim agora

2024-01-26 18:10 UTC, merged