Feat/user type switch
Carpool-Tech/carpool-app pull request #41
Opened 2024-01-30 13:39 UTC by marianaantunes

![image](https://github.com/Carpool-Tech/carpool-app/assets/46333060/94e5ccf4-50d3-435d-9871-f86b0a9667f9)

2024-01-30 13:52 UTC, maykelnekel requested changes
Acredito que estão faltando alguns componentes.
Não encontrei nessa versão o CardFaq, Map e NavigationBar. Será que é porque não foram modificados?
Mas estranho estar entrando várias alterações de arquivos que já eram para estar nessa branch.

Precisamos confirmar se está tudo atualizado antes de realizar o merge.

2024-01-30 13:52 UTC, maykelnekel commented on app/components/DriverPassengerSwitch/index.tsx
A estrutura ficou muito boa, porém acredito que podemos deixar esse componente mais reutilizável.

2024-01-30 13:52 UTC, maykelnekel commented on app/components/DriverPassengerSwitch/index.tsx
Por exemplo: Recebendo o ícone, título e texto por prop.
Como fiz com o Card Faq por exemplo.

2024-01-30 13:57 UTC, marianaantunes commented on app/components/DriverPassengerSwitch/index.tsx
boa, vou extrair a funcionalidade pra um outro componente

2024-01-30 17:56 UTC, nekelpatrick commented
Tem algum motivo específico pra esse MR não ter sido apontado ao #40?

2024-01-30 19:12 UTC, marianaantunes commented
Na verdade só não tinha visto, mas antes de dar merge já ia conferir, mas obrigada por avisar @nekelpatrick 🙌

2024-01-31 16:31 UTC, maykelnekel approved these changes
Tudo certo para mim!

2024-01-31 17:08 UTC, merged